import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import NoteBody from "./components/Evernote/NoteBody";
import NoteOperations from "./components/Evernote/NoteOperations";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='grid grid-cols-3 gap-4 border-t-2 border-black'>
				<div className='  h-full'>
					<NoteOperations />
					<div className='m-2'></div>
				</div>
				<div className='col-span-2 mt-1'>
					<NoteBody />
				</div>
			</main>
		</div>
	);
}
